data:
  grid_dim: 60 # changed for gan
  batch_size: 2
  num_workers: 4
  val_split: 0.2

unet3d:
  layers_per_block: 5
  block_out_channels: [32, 64, 128, 256, 512, 1024]
  down_block_types:
    - "DownBlock3D"
    - "DownBlock3D" 
    - "DownBlock3D" 
    - "DownBlock3D"
    - "CrossAttnDownBlock3D"
    - "DownBlock3D"
  up_block_types:
    - "UpBlock3D"
    - "CrossAttnUpBlock3D"
    - "UpBlock3D"
    - "UpBlock3D"
    - "UpBlock3D"
    - "UpBlock3D"

scheduler:
  num_train_timesteps: 1000
  beta_schedule: "squaredcos_cap_v2"

guidance:
  scale: 7.5
  drop_proba: 0.1
